name: Validate

on:
  push:
  pull_request:

jobs:
  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

  tests:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest homeassistant

      - name: "Run pytest"
        run: pytest tests/ -v 